
syn.queue_on_teleport(tostring("https://raw.githubusercontent.com/gmoney69420/EggOpen/main/EggOpen.lua"))
local playername = game.Players.LocalPlayer.Name
local ts = game:GetService("TeleportService")
local p = game:GetService("Players").LocalPlayer
character = game.Workspace:WaitForChild("robowizardmonkey") 
function walktopoint(position)
character.Humanoid.WalkToPoint = position
end
walktopoint(Vector3.new(4527, -14, 2349))
wait(1)
getgenv().prepteleport = false
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
  [1] = "b",
  [2] = "buy egg"
}

workspace.__THINGS.__REMOTES.MAIN:FireServer(unpack(args))
wait(1.5)

function eggopen()
  spawn(function()
    while prepteleport == false do
    local args = {
      [1] = {
          [1] = "Rainbow Pixel Egg",
          [2] = true
      }
    }
    workspace.__THINGS.__REMOTES:FindFirstChild("buy egg"):InvokeServer(unpack(args))
    wait()
  end
  end)
  
end
function TeleInit()
  spawn(function()
    wait(60)
    prepteleport = true
    print("bye")
    wait(3)
    
    ts:Teleport(game.PlaceId, p)
  end)
  
end

function RemoveInvNoti()
  spawn(function()
    while true do
    local notif = game:GetService("Players").LocalPlayer.PlayerGui
    if notif.Main.Bottom.Inventory.Notification.Count.text > "998" then do
        notif.Inventory.Enabled = true
        task.wait(1)
        notif.Inventory.Enabled = false
    end
    end
    task.wait(0.0001)
    end
    
  end)
  
end







-- Script generated by SimpleSpy - credits to exx#9394
getsenv(game.Players[playername].PlayerScripts.Scripts.Game["Open Eggs"]).OpenEgg = function() return end
eggopen()
TeleInit()
RemoveInvNoti()
